# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYRefreshDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYRefreshDemo
  pod 'MJRefresh', '~> 3.1.12'
  pod 'DZNEmptyDataSet'
end
